name: Build Discover Mesic Back and front

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main

jobs:
  build-and-deploy-back:
    name: Build and Deploy Back-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets. DOCKER_USERNAME }}
        password: s{{ secrets.DOCKER_PASSWORD }}
        repository: amanbc/api-discover-mesic
        dockerfile: api/Dockerfile
        tags: latest

  build-and-deploy-front:
    name: Build and Dep loy Front-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.D0CKER_USERNAME }}
        password: $t{ secrets.DOCKER_PASSWORD }}
        repository: amanbc/app-discover-mesic
        dockerfile: app/Dockerfile
        tags: latest